### ISSUE TITLE
关于代码获取

### ISSUE THREAD

**Issue by bing170215** [HillZhang1999/CTC-Report#1]
作者您好，我看了您们团队在CTC2021比赛中所用方法的报告，我想学习一下，所以请问一下能否方便提供一下你们实现的整个纠错流程的源代码，仅供学习使用。本人邮箱：gyu170215@163.com ，如果方便提供源代码，麻烦联系我一下，谢谢。

**Comment by HillZhang1999** [comment]
我们后续计划开源一系列中文纠错的baseline，敬请期待

**Comment by Vivicai1005** [comment]
> 我们后续计划开源一系列中文纠错的baseline，敬请期待

您好，您们打算什么时候开源中文纠错的baseline模型呢？

**Comment by HillZhang1999** [comment]
> > 我们后续计划开源一系列中文纠错的baseline，敬请期待
> 
> 您好，您们打算什么时候开源中文纠错的baseline模型呢？

争取在年前开源，并且还会提供其他中文纠错的新资源，敬请期待
