### ISSUE TITLE
GECToR训练

### ISSUE THREAD

**Issue by Martine307** [HillZhang1999/CTC-Report#3]
你好，打扰了，我在训练中文gector模型时，使用大量伪数据训练的效果，与直接在任务数据微调效果差不多。想请问下：1）你们在ctc比赛中的方案，只做伪数据预训（不做任务微调）可以达到什么效果呢？（或者有测试过ctc提供的baseline模型效果吗）2）你们训练gector的代码是基于ctc比赛提供的代码修改的吗？感谢。

**Comment by HillZhang1999** [comment]
Hi，你好。
1）我们在评测报告中汇报的所有GEC模型结果，并未经过任何真实数据微调，具体指标可以参考我们的评测报告。原因是：我们发现无论是使用Lang8还是HSK数据集（二语学习者领域）微调预训练模型，在CTC的资格集上，都没有显著提升，甚至会有所下降。对于该现象，我们简单分析了二语学习者和CTC母语文本数据分布的领域差异，将其归因于该差异。但是，在上述真实数据集上微调，对于NLPCC18测试集的性能，会有非常显著的提升，原因是NLPCC18测试集也来自于二语学习者文本。
2）我们训练GECToR的代码，来自于对[官方GECToR仓库](https://github.com/grammarly/gector)的修改，并未使用主办方提供的代码。在官方代码基础上，我们还额外进行了一些中文适配和训练加速。

**Comment by Martine307** [comment]
感谢你的回复，我使用大量数据预训练gector后，在ctc验证集并没有带来提升（score只有20左右），目前还没确定是训练参数还是主办方代码的问题。想问下是否方便提供下预训阶段的训练参数呢？多谢了。

**Comment by HillZhang1999** [comment]
主要参数：

- 训练集规模：15M（错误率100%）
- 词表大小：8K
- 训练轮数：5（前2轮不微调BERT）
- 学习率：1e-5（前两轮1e-3）
- 批次大小：64
- 梯度累计：2
- 最大句长：200

其余参数可参考英文GECToR。

**Comment by Martine307** [comment]
多谢！
