### ISSUE TITLE
Wiki-Edits数据集

### ISSUE THREAD

**Issue by wangwang110** [HillZhang1999/CTC-Report#6]
感谢公开解决方案，请问 Wiki-Edits数据怎么获取呢？

**Comment by HillZhang1999** [comment]
你好，这个数据集规模比较大，我们暂时不考虑开源。
不过最近有看到其他同学做了和我们思路类似的工作：https://github.com/xueyouluo/wiki-error-extract
你可以参考。

**Comment by wangwang110** [comment]
> 你好，这个数据集规模比较大，我们暂时不考虑开源。 不过最近有看到其他同学做了和我们思路类似的工作：https://github.com/xueyouluo/wiki-error-extract 你可以参考。

好的，感谢
