### ISSUE TITLE
语义模板的语病纠错

### ISSUE THREAD

**Issue by ZTurboX** [HillZhang1999/CTC-Report#7]
自动抽取语义模板具体是怎么做的？是用现代汉语实词搭配词典做的吗？

**Comment by HillZhang1999** [comment]
具体可看论文3.3节。我们先设计模板（比如A...B是语病吗），根据模板去搜索引擎里爬取相关问题（大约...左右是语病吗），然后利用困惑度找到最优修改方式（删除大约还是左右）。
