### ISSUE TITLE
拼写纠错

### ISSUE THREAD

**Issue by ZTurboX** [HillZhang1999/CTC-Report#8]
拼写纠错模型是不是类似于pycorrector开源项目中macbert4csc?另外，拼写纠错中的解码trick是在预测时使用吗？在训练时要使用吗？

**Comment by HillZhang1999** [comment]
1）是的，模型结构上没有什么特别的地方，我们主要关注数据层面；
2）trick仅在预测使用，训练不用。最近也有一些在训练时使用类似trick的工作，可以参考https://arxiv.org/abs/2203.00991

**Comment by ZTurboX** [comment]
> 1）是的，模型结构上没有什么特别的地方，我们主要关注数据层面； 2）trick仅在预测使用，训练不用。最近也有一些在训练时使用类似trick的工作，可以参考https://arxiv.org/abs/2203.00991

谢谢。用macbert4csc模型做过拼写纠错，目前想做落地应用，但模型预测性能方面还达不到，目前在encode部分探索一些小模型和模型的蒸馏剪裁

**Comment by ZTurboX** [comment]
“对每 10 个词的片段随机挑选 1 个位置植入错误。” 随机挑选需要选择词语频率大的吗？如果同音词存在多个，是多次替换吗？

**Comment by HillZhang1999** [comment]
> “对每 10 个词的片段随机挑选 1 个位置植入错误。” 随机挑选需要选择词语频率大的吗？如果同音词存在多个，是多次替换吗？

@zhentaoCoding 1）我们没有按照词频采样，实际上在语法纠错任务中我们尝试过，但效果没有显著提升；2）存在多个也是随机采样1个替换；
实际上这些都是比较tricky的方案，我们也没有进行严格的消融实验，您可以多尝试尝试。

**Comment by ZTurboX** [comment]
gector适配中文需要改动的多吗

**Comment by HillZhang1999** [comment]
> gector适配中文需要改动的多吗

@zhentaoCoding 不多，我们这个月应该会把相关代码开源

**Comment by ZTurboX** [comment]
语法纠错中，插入、交换到附近位置，这里的附近是在相邻吗，还是在一个窗口内

**Comment by HillZhang1999** [comment]
> 语法纠错中，插入、交换到附近位置，这里的附近是在相邻吗，还是在一个窗口内

你说的是SWAP这个标签吗？这个是在+-8个字符的窗口内。不过现在我们发现即使用了该标签，基于Seq2Edit的模型对于需要调序的错误性能依旧不足，推荐使用基于Seq2Seq的模型解决此类错误。
