### ISSUE TITLE
请问“基于最小编辑距离算法的标签抽取方法”具体是怎么写的？

### ISSUE THREAD

**Issue by yucc-leon** [HillZhang1999/CTC-Report#9]
看示例愣是没想明白怎么做的，直觉上对于改动点比较多的平行文本，抽出来的标签准确性不会太高吧？另，翘首以盼开源ing……

**Comment by HillZhang1999** [comment]
首先，这里的标签抽取肯定是不会出错的，即通过错误文本和抽取出的标签百分百可以还原正确文本，唯一的问题是最小编辑距离的编辑序列不唯一，如何选取一条最佳序列值得研究，我们之前也做了一些探索，利用一些先验语言学知识可以选择更好的序列。

代码的话，我们的论文刚刚录用，需要一些时间来整理，我们会开源新的数据集、评价指标以及两种模型（Seq2Edit、Seq2Seq），请耐心等待 :)

**Comment by yucc-leon** [comment]
感谢回复~
